apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    build: jenkins-slave-maven-rhel7-scap
  name: jenkins-slave-maven-rhel7-scap
spec:
  output:
    pushSecret:
      name: artifactory
    to:
      kind: DockerImage
      name: repository.fismobile.com:6555/jenkinsimages/jenkins-slave-maven-rhel7-fortify:scap
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7
      USER root

      RUN yum --enablerepo="rhel-7-server-extras-rpms" --enablerepo="rhel-7-server-optional-rpms" -y install libassuan-devel \
        ostree-devel runc skopeo-containers openscap-utils scap-security-guide

      # Install buildah thru fedora
      RUN curl -o buildah-0.4.1.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/buildah/0.4/1.git9cbccf8.fc27/x86_64/buildah-0.4-1.git9cbccf8.fc27.x86_64.rpm && \
        rpm -ivh buildah-0.4.1.x86_64.rpm && yum -y install buildah && \
        rm buildah-0.4.1.x86_64.rpm

      USER 1001
    type: Dockerfile
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers: []
status:
  lastVersion: 0
