apiVersion: v1
kind: Template
metadata:
  name: scan-image-template
  annotations:
    openshift.io/display-name: Image Scanning Base
    description: Template to create a base image for scanning images
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhel7
  spec:
    dockerImageRepository: registry.access.redhat.com/rhel7/rhel
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      type: Binary
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel7:7.4
      type: Docker
parameters:
- name: NAME
  displayName: Name
  description: Name Applied to the Resulting ImageStream and BuildConfig
  value: image-scan-base
  required: true
