apiVersion: v1
kind: Template
metadata:
  name: scan-image-template
  annotations:
    openshift.io/display-name: Scan Image
    description: Template to create a Job to Scan an Image
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: "scan-image-${UNIQUE_VALUE}"
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: "scan-image-${UNIQUE_VALUE}"
      spec:
        containers:
        - name: scan-image
          image: image-scan-base
          command:
            - "/bin/bash"
            - "-c"
            - >
              sudo buildah from registry.access.redhat.com/rhel7.4
              sudo buildah mount rhel7.4-working-container
              sudo ls /var/lib/containers
              sudo ls /var/lib/containers/storage
              sudo oscap-chroot /var/lib/containers/storage/overlay/dafb9ee7e8f9a774242afae1c5dce5b357cb1dfcb020bed629092b0cf21e2bfe/merged oval eval --results oval-results.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-rhel7-oval.xml
          securityContext:
            privileged: true
        restartPolicy: OnFailure
        serviceAccount: ${SERVICE_ACCOUNT_NAME}
parameters:
- name: SERVICE_ACCOUNT_NAME
  displayName: Service Account Name
  description: Name of the service account to Run the Job As
  value: imagemanager
  required: true
- name: IMAGE_TO_SCAN
  displayName: Image to Scan
  description: Image to Scan
  required: true
  value: registry.access.redhat.com/rhel7.4
- name: UNIQUE_VALUE
  generate: expression
  from: "[a-z0-9]{5}"
  required: true
